<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cas</string>
	</array>
	<key>name</key>
	<string>Caseum</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(import|extern)</string>
			<key>name</key>
			<string>keyword.caseum</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\".+\"</string>
			<key>name</key>
			<string>string.quoted.double.caseum</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(/)(/)(.*)(\n)</string>
			<key>name</key>
			<string>comment.line.double-slash.caseum</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(if|for)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.caseum</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.block.caseum</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.caseum</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>type declaration</string>
			<key>match</key>
			<string>(\[)(int|string|double|void)(\])</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(#)(\[)(.+)(\])([A-z0-9]+)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.caseum</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.caseum</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.caseum</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function definition</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.function.plain.caseum</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>constants, like 2413 or 0x24A</string>
			<key>match</key>
			<string>(([0][x][A-Z0-9]+)|([0-9]+))</string>
			<key>name</key>
			<string>constant.numeric.caseum</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.any-call.caseum</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>function calls</string>
			<key>match</key>
			<string>(([A-z]+[0-9]*)+)(\()</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.caseum</string>
	<key>uuid</key>
	<string>f42f37ee-69d8-4b5b-9778-7c4b14c2f638</string>
</dict>
</plist>
